# -*- coding: utf-8 -*-
"""team-selector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oC5xGTAUMfJLgCuktyvG7c28Uxxn9-5X
"""

import pandas as pd
import xlsxwriter
import tkinter as tk
from tkinter import filedialog

max_teams_per_case = int(input("How many teams per Case? "))
name = str(input("How should the output file be named? [without xls] "))

data = pd.read_excel("Test_Jotform.xlsx")
df = pd.DataFrame(data)
df.drop_duplicates(subset='Team', keep= "first", inplace = True)
df = df.sample(frac=1).reset_index(drop=True)

cases = list(set(df["Präferenz 1"].tolist() + df["Präferenz 2"].tolist()))
selection = dict()
for case in cases:
  selection[case] = []

overflow = []

for index, row in df.iterrows():
    if len(selection[row["Präferenz 1"]]) < max_teams_per_case:
      selection[row["Präferenz 1"]].append(row["Team"])

    elif len(selection[row["Präferenz 2"]]) < max_teams_per_case:
      selection[row["Präferenz 2"]].append(row["Team"])

    else:
      overflow.append(row["Team"])

for team in overflow:
  selection[df[df['Team']== team]["Präferenz 1"].values[0]].append(team)

ouput = pd.DataFrame(dict([ (k,pd.Series(v)) for k,v in selection.items() ]))

# ouput.to_excel(name + ".xlsx", index = False, header=True)

root= tk.Tk()

canvas1 = tk.Canvas(root, width = 300, height = 300, bg = 'lightsteelblue2', relief = 'raised')
canvas1.pack()

def exportExcel ():
    global output
    
    export_file_path = filedialog.asksaveasfilename(defaultextension='.xlsx')
    output.to_excel (export_file_path, index = False, header=True)

saveAsButtonExcel = tk.Button(text='Export Excel', command=exportExcel, bg='green', fg='white', font=('helvetica', 12, 'bold'))
canvas1.create_window(150, 150, window=saveAsButtonExcel)

root.mainloop()